#!/usr/bin/env python3

"""Tester module. This should implement unit tests for any important functionalities."""

import os, sys
import unittest
import glob

import utility

class TestUtilities(unittest.TestCase):
    """Class testing all utility functions."""
    def test_augment_img_set(self):
        """Tests the image augmentation."""
        # Make sure there is only a single image
        self.assertEqual(len(glob.glob("../assets/test/test_img*.jpg")), 1,
                         msg="Too many test files in folder. Please ensure that the augmentation" +
                             " was not already run")

        # Test the augmentation
        utility.augment_img_set("../assets/test/")
        img_count = len([1 for file in glob.glob("../assets/test/test_img*.jpg")])
        self.assertEqual(img_count, 8, msg="Not correct number of images generated by augmenting " +
                                           " test_img.jpg file")


class TestCnnModel(unittest.TestCase):
    """Class testing the CNN model."""


if __name__ == "__main__":
    unittest.main()
